# Generated by Django 4.0.2 on 2022-03-14 11:46

import django.core.validators
from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
                ('description', models.TextField(max_length=1000)),
                ('image', models.ImageField(upload_to='About')),
                ('cv_upload', models.FileField(upload_to='About')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, validators=[django.core.validators.RegexValidator('^(([A-Za-z]+)(\\s[A-Za-z]+)?)$', 'only string is allowed')])),
                ('email', models.EmailField(max_length=254, validators=[django.core.validators.RegexValidator('\\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\\.[A-Z|a-z]{2,}\\b')])),
                ('subject', models.CharField(max_length=40, validators=[django.core.validators.RegexValidator('^(([A-Za-z]+)(\\s[A-Za-z]+)?)$', 'only string is allowed')])),
                ('message', models.TextField(max_length=2000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution_name', models.CharField(max_length=100)),
                ('level', models.CharField(max_length=100)),
                ('start_year', models.DateField(null=True)),
                ('end_year', models.DateField(null=True)),
                ('show', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experience_name', models.CharField(choices=[('Training', 'Training'), ('Internship', 'Internship'), ('Work', 'Work')], default='Training', max_length=100)),
                ('responsiblity', models.TextField(max_length=500, null=True)),
                ('platform', models.CharField(default='programming', max_length=100)),
                ('start_year', models.DateField(null=True)),
                ('end_year', models.DateField(null=True)),
                ('show', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Intrests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('icon', models.ImageField(upload_to='Intrests')),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('Design', 'Design'), ('PHP', 'PHP'), ('Python', 'Python'), ('Wordpress', 'Wordpress')], default='Design', max_length=100)),
                ('client', models.CharField(default='none', max_length=100, null=True)),
                ('description', models.TextField(default='none', max_length=1000, null=True)),
                ('publish_date', models.DateField(default='2022-01-01', null=True)),
                ('link', models.TextField(max_length=200, null=True)),
                ('image', models.ImageField(null=True, upload_to='Portfolio')),
                ('show', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('description', models.TextField(max_length=1000)),
                ('icon', models.ImageField(upload_to='Service')),
                ('show', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(max_length=100, null=True, validators=[django.core.validators.RegexValidator('^(([A-Za-z]+)(\\s[A-Za-z]+)?)$', 'only string is allowed')])),
                ('image', models.ImageField(upload_to='skills', validators=[django.core.validators.RegexValidator('([^\\s]+(\\.(?i)(jpe?g|png|gif|bmp))$)', 'only jpg, jepg, png, gif, bmp images are allowed')])),
                ('percentage', models.IntegerField()),
                ('show', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Social',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('icon', models.ImageField(upload_to='Social')),
                ('link', models.CharField(max_length=100)),
                ('show', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('happy_client_no', models.IntegerField(null=True)),
                ('support_hour', models.IntegerField(null=True)),
                ('award_no', models.IntegerField(null=True)),
                ('show', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Testimonials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100)),
                ('post', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=1000)),
                ('image', models.ImageField(upload_to='Testimonials')),
                ('show', models.BooleanField(default=False)),
            ],
        ),
    ]
